### PR TITLE
Fix: navigation , list , form , card

### PR DESCRIPTION
**Pull request by Divya70**
update code of navigation , cards, list and input component
update inputs 
update cards 
update navigation 
update list

### CODE REVIEW

**Review by NamrataRaikwar2002 — APPROVED** [review]

**Comment by aman11s** [comment]
Screenshot 2022-02-20 at 8 46 37 PM
There is a white space below the footer on homepage.

**Comment by aman11s** [comment]
Screenshot 2022-02-20 at 8 48 19 PM

- Add some margin above the footer.

**Comment by aman11s** [comment]
Screenshot 2022-02-20 at 8 50 42 PM

- In the input component, code snippet don't have a left margin. Add some left margin.

**Review by Ayushi20-19 — APPROVED** [review]

**Review by aman11s — APPROVED** [review]
Just a few suggestions. The rest looks good.

**Pull request merged**
